//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineLogUploader.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaInfoCenterDb : DbContext
    {
        public BaInfoCenterDb()
            : base("name=BaInfoCenterDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SML_MaterialMaster> SML_MaterialMaster { get; set; }
        public virtual DbSet<SML_MaterialScanIn> SML_MaterialScanIn { get; set; }
        public virtual DbSet<SML_MaterialScanOut> SML_MaterialScanOut { get; set; }
    }
}
