//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineLogUploader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotProgress
    {
        public string LotNo { get; set; }
        public string LotNoSuffix { get; set; }
        public string Type { get; set; }
        public string ProductCode { get; set; }
        public string ProductFamily { get; set; }
        public string ProductCateg { get; set; }
        public string OrderNo { get; set; }
        public int ProcessSeqNo { get; set; }
        public string ProcessCode { get; set; }
        public string ProcessName { get; set; }
        public Nullable<System.DateTime> StartPlanTime { get; set; }
        public Nullable<System.DateTime> EndPlanTime { get; set; }
        public string MachineNo { get; set; }
        public string MachineName { get; set; }
        public string LineID { get; set; }
        public string LineName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string StartOperatorID { get; set; }
        public string StartOperatorName { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string EndOperatorID { get; set; }
        public string EndOperatorName { get; set; }
        public Nullable<int> InputQty { get; set; }
        public Nullable<int> SubInputQty { get; set; }
        public Nullable<decimal> InputLotCount { get; set; }
        public Nullable<int> SurplusInQty { get; set; }
        public Nullable<int> SubSurplusInQty { get; set; }
        public Nullable<int> TotalBlendInQty { get; set; }
        public Nullable<int> SubTotalBlendInQty { get; set; }
        public string InputUnit { get; set; }
        public string InputUnitName { get; set; }
        public Nullable<int> OutputQty { get; set; }
        public Nullable<int> SubOutputQty { get; set; }
        public Nullable<decimal> OutputLotCount { get; set; }
        public Nullable<int> TotalDefectQty { get; set; }
        public Nullable<int> SubTotalDefectQty { get; set; }
        public Nullable<int> SurplusOutQty { get; set; }
        public Nullable<int> SubSurplusOutQty { get; set; }
        public Nullable<int> TotalBlendOutQty { get; set; }
        public Nullable<int> SubTotalBlendOutQty { get; set; }
        public Nullable<int> SampleQty { get; set; }
        public Nullable<int> SubSampleQty { get; set; }
        public Nullable<int> UnclearQty { get; set; }
        public Nullable<int> SubUnclearQty { get; set; }
        public string OutputUnit { get; set; }
        public string OutputUnitName { get; set; }
        public Nullable<System.DateTime> MachineStartTime { get; set; }
        public Nullable<System.DateTime> MachineEndTime { get; set; }
        public string MachineProductionTime { get; set; }
        public string MachineStopTime { get; set; }
        public string MachineAlarmTime { get; set; }
        public bool ProductEnd { get; set; }
        public bool WIPControlEnd { get; set; }
        public bool TotalDefectEnd { get; set; }
        public bool DailyAnalysisCheck { get; set; }
        public bool OptionalProcess { get; set; }
        public string QtyCheck { get; set; }
        public string DefectCheck { get; set; }
        public bool DeletePermission { get; set; }
        public bool HavingSmallProcess { get; set; }
        public string StartCarrierSet { get; set; }
        public string StartCarrierCheck { get; set; }
        public string EndCarrierSet { get; set; }
        public string EndCarrierCheck { get; set; }
        public string UpdateCarrierEnd { get; set; }
        public string UpdateMaterialEnd { get; set; }
        public string UpdateToolEnd { get; set; }
        public string SplitLot { get; set; }
        public string SurplusSucceed { get; set; }
        public string RegistType { get; set; }
        public string NCNNo { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime UpdDate { get; set; }
        public string UserName { get; set; }
        public string ComputerName { get; set; }
    }
}
