//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineLogUploader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SML_Machine_Register
    {
        public int MachineRegisterId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Section { get; set; }
        public string Url { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public string ChangedBy { get; set; }
        public string Remark { get; set; }
    }
}
