//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineLogUploader.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMLPORTALEntities : DbContext
    {
        public SMLPORTALEntities()
            : base("name=SMLPORTALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SML_Machine_Register> SML_Machine_Register { get; set; }
        public virtual DbSet<SML_Machine_Logger> SML_Machine_Logger { get; set; }
    }
}
